"""empty message

Revision ID: 41a27d9b84d2
Revises: 
Create Date: 2019-01-05 15:53:28.761816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '41a27d9b84d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('grid_id', sa.String(length=16), nullable=True),
    sa.Column('week', sa.String(length=16), nullable=True),
    sa.Column('stay', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_traffic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consumption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mobile_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('grid_id', sa.String(length=16), nullable=True),
    sa.Column('box', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid')
    op.drop_table('detail')
    # ### end Alembic commands ###
