"""empty message

Revision ID: 4981f1746711
Revises: 41a27d9b84d2
Create Date: 2019-01-05 21:57:50.449457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4981f1746711'
down_revision = '41a27d9b84d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(length=128), nullable=True),
    sa.Column('day', sa.String(length=16), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_grid_box', table_name='grid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_grid_box', 'grid', ['box'], unique=False)
    op.drop_table('user')
    op.drop_table('access')
    # ### end Alembic commands ###
