"""empty message

Revision ID: 6fae85570d68
Revises: 
Create Date: 2019-01-02 12:42:50.361271

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6fae85570d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('grid_id', sa.String(length=16), nullable=True),
    sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('box', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid')
    # ### end Alembic commands ###
