"""empty message

Revision ID: 84289291dc72
Revises: 
Create Date: 2019-01-06 20:27:24.730237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '84289291dc72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(length=128), nullable=True),
    sa.Column('day', sa.String(length=16), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('grid_id', sa.String(length=16), nullable=True),
    sa.Column('week', sa.String(length=16), nullable=True),
    sa.Column('stay', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_traffic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consumption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mobile_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_city'), 'detail', ['city'], unique=False)
    op.create_index(op.f('ix_detail_grid_id'), 'detail', ['grid_id'], unique=False)
    op.create_index(op.f('ix_detail_week'), 'detail', ['week'], unique=False)
    op.create_table('grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('grid_id', sa.String(length=16), nullable=True),
    sa.Column('box', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('grid')
    op.drop_index(op.f('ix_detail_week'), table_name='detail')
    op.drop_index(op.f('ix_detail_grid_id'), table_name='detail')
    op.drop_index(op.f('ix_detail_city'), table_name='detail')
    op.drop_table('detail')
    op.drop_table('access')
    # ### end Alembic commands ###
