"""empty message

Revision ID: 9a37a14e95c7
Revises: 84289291dc72
Create Date: 2019-01-07 14:48:38.890443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a37a14e95c7'
down_revision = '84289291dc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('internet', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_grid_box', table_name='grid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_grid_box', 'grid', ['box'], unique=False)
    op.drop_column('detail', 'internet')
    # ### end Alembic commands ###
