SQLALCHEMY_DATABASE_URI = 'postgresql://<username>:<password>@<ip>:<port>/<db>'
EXPIRE_TIME = 3000
MAX_DAY_ACCESS = 5000
LOG_FILE = 'xxx/flask.log'
SQLALCHEMY_POOL_SIZE=100
SQLALCHEMY_POOL_TIMEOUT=200