#!/usr/bin/env bash

set -eu

readonly WARNING="Usage: insert_sql grid|detail|dupdate|all [-s sql] city [week1 week2 ...]"
if [[ $# -eq 0 ]]; then
    echo "$WARNING"
    exit 1
fi

POSITIONAL=()

PG=local-postgis
I_DIR=./data/tar

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        -d|--database)
            PG="$2"
            shift
            shift
            ;;
        -i|--input-dir)
            I_DIR="$2"
            shift
            shift
            ;;
        -s|--sql)
            SQL="$2"
            shift
            shift
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done

set -- "${POSITIONAL[@]}"

case "$1" in
    grid)
        city=$2
        if [[ $# -lt 2 ]]; then
            echo "$WARNING"
            exit 1
        fi
        gunzip -c "${I_DIR}/${city}_grid.sql.gz" |docker exec -i ${PG} psql -U postgres -d postgres
        ;;
    detail)
        city=$2
        if [[ $# -lt 3 ]]; then
            echo "$WARNING"
            exit 1
        fi
        for week in "${@:3}"; do
            tar_file="${I_DIR}/${city}_${week}_detail.sql.tar.gz"
            echo "Handling $tar_file ..."
            tar tf ${tar_file}  | while read line; do
                echo "...insert ${line}"
                tar xzOf ${tar_file} ${line}|docker exec -i ${PG} psql -U postgres -d postgres
            done
        done
        ;;
    dupdate)
        gunzip -c "$SQL" |docker exec -i ${PG} psql -U postgres -d postgres
        ;;
    all)
        total=$(ls "$I_DIR"|wc -l)
        i=0
        for file in $(ls "$I_DIR");do
            start=$(date "+%s")
            if [[ "$file" == *grid.sql.gz ]]; then
                echo "insert $file"
                gunzip -c "$I_DIR/$file" |docker exec -i ${PG} psql -U postgres -d postgres
            elif [[ "$file" == *deta




            il.sql.tar.gz ]]; then
                echo "insert $file"
                tar tf "$I_DIR/$file"  | while read line; do
                    echo "....insert $line"
                    tar xzOf "$I_DIR/$file" "$line"|docker exec -i ${PG} psql -U postgres -d postgres
                done
            fi
            now=$(date "+%s")
            time=$((now-start))
            i=$((i+1))
            echo "TIME_USED:$time seconds. $i/$total."
        done

        ;;
    *)
        echo "$WARNING"
        exit 1
        ;;
esac